spring.application.name=fraud
# AWS RDS MySQL connection URL — replace <endpoint> with your actual RDS endpoint
spring.datasource.url=jdbc:mysql://fraud-monitor-db.cxkkk4o2e2w9.ca-central-1.rds.amazonaws.com:3306/frauddb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

# RDS master username you set during creation
spring.datasource.username=admin

# RDS master password you set during creation
spring.datasource.password=Qwerty654321#

# MySQL driver class
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate configs
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.security.user.name=
spring.security.user.password=
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

